#!/usr/bin/env python3
"""Regenerate reference fragments and the rule matrix from the deployed-stack sources."""
import csv
import argparse
import io
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parents[1]
SECURITY_TYPES = {"AWS::EC2::SecurityGroup", "AWS::EC2::SecurityGroupIngress", "AWS::EC2::SecurityGroupEgress"}


def reference(value):
    if isinstance(value, str):
        return value
    if "Ref" in value:
        return value["Ref"]
    if "Fn::ImportValue" in value:
        return reference(value["Fn::ImportValue"])
    if "Fn::Sub" in value:
        return value["Fn::Sub"]
    return str(value)


def ports(rule):
    if str(rule["IpProtocol"]) == "-1":
        return "ALL", "ALL"
    return str(rule["IpProtocol"]), f"{rule['FromPort']}-{rule['ToPort']}"


def generate(check=False):
    rows = []
    stale = []

    def save(path, content):
        if check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(content)
    for name in ("01-network-stack.yaml", "02-core-infrastructure-stack.yaml", "04-microservice-stack.yaml"):
        template = yaml.safe_load((ROOT / "cloudformation" / name).read_text())
        resources = template["Resources"]
        if not name.startswith("01"):
            fragment = {key: value for key, value in resources.items() if value["Type"] in SECURITY_TYPES}
            prefix = "02-core" if name.startswith("02") else "04-microservice"
            filename = prefix + "-security-resources.fragment.yaml"
            header = f"# Generated by scripts/sync_security_reference.py from {name}.\n# Reference snapshot only. Do not deploy separately or merge duplicate resources into the full stack.\n"
            save(ROOT / "cloudformation" / filename, header + yaml.safe_dump({"Resources": fragment}, sort_keys=False))
        for key, resource in resources.items():
            kind, properties = resource["Type"], resource.get("Properties", {})
            if kind == "AWS::EC2::SecurityGroup":
                for direction, field in (("Inbound", "SecurityGroupIngress"), ("Outbound", "SecurityGroupEgress")):
                    for rule in properties.get(field, []):
                        protocol, port = ports(rule)
                        peer = next((reference(rule[k]) for k in ("CidrIp", "CidrIpv6", "SourceSecurityGroupId", "DestinationSecurityGroupId") if k in rule), "unspecified")
                        rows.append(["SG", key, direction, protocol, port, peer, rule.get("Description", ""), name])
            elif kind in SECURITY_TYPES:
                protocol, port = ports(properties)
                peer = next((reference(properties[k]) for k in ("CidrIp", "CidrIpv6", "SourceSecurityGroupId", "DestinationSecurityGroupId") if k in properties), "unspecified")
                rows.append(["SG", reference(properties["GroupId"]), "Inbound" if kind.endswith("Ingress") else "Outbound",
                             protocol, port, peer, properties.get("Description", ""), name])
            elif kind == "AWS::EC2::NetworkAclEntry":
                rule = properties.get("PortRange", {})
                port = f"{rule['From']}-{rule['To']}" if rule else "ALL"
                rows.append(["NACL", reference(properties["NetworkAclId"]), "Outbound" if properties["Egress"] else "Inbound",
                             str(properties["Protocol"]), port, reference(properties["CidrBlock"]),
                             f"{properties['RuleAction'].upper()} rule {properties['RuleNumber']}; {key}", name])
    output = io.StringIO(newline="")
    writer = csv.writer(output, lineterminator="\n")
    writer.writerow(["ControlType", "Name", "Direction", "Protocol", "PortRange", "Source/Destination", "Purpose", "StackOwner"])
    writer.writerows(rows)
    save(ROOT / "cloudformation" / "Part07_Security_Group_and_NACL_Matrix.csv", output.getvalue())
    if stale:
        raise ValueError("Stale security references: " + ", ".join(stale) + "; run scripts/sync_security_reference.py")
    return len(rows)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Compare without writing")
    args = parser.parse_args()
    print(f"{'Checked' if args.check else 'Generated'} current security fragments and {generate(args.check)} rule rows.")
